on:
  push:
    tags:
      # Regex for a version number such as 0.2.1
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build for Linux
        run: cargo build --release

      - name: Archive Linux build
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: target/release/

  release:
    runs-on: macos-latest

    needs: build

    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build for macOS
        run: cargo build --release

      - name: Archive macOS build
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: target/release/

  windows:
    runs-on: windows-latest

    needs: build

    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build for Windows
        run: cargo build --release

      - name: Archive Windows build
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: target/release/