name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Lint-and-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check cargo version
      run: cargo --version
    - name: Check syntax
      run: cargo check --all-targets --all-features
    - name: Check format
      run: cargo fmt --all -- --check
    - name: Check lint
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Test
      run: cargo test --verbose