name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Lint-and-Test:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v3
    - name: Format and Lint
      run: cargo fmt --all -- --check && cargo clippy --all-targets --all-features -- -D warnings
    - name: Tests
      run: cargo test --verbose